from dotenv import load_dotenv
import os

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))


def env(name, default=None):
    return os.getenv(name, default)


APIKEy = env("APIKEy")
APIKEyTMDB = env("APIKEYTMDB", env("APIKEyTMDB"))
DB_DRIVER = env("DB_DRIVER", "ODBC Driver 17 for SQL Server")
DB_SERVER = env("DB_SERVER", "10.55.55.134\\SQLDEV")
DB_DATABASE = env("DB_DATABASE", "Programacion")
DB_UID = env("DB_UID", "admin_sql")
DB_PWD = env("DB_PWD", "ProgramacionPoderos0*")
DB_TRUST_SERVER_CERTIFICATE = env("DB_TRUST_SERVER_CERTIFICATE", "yes")

COMSCORE_WATCH_FOLDER = env("COMSCORE_WATCH_FOLDER")
COMSCORE_FILE_PATTERN = env("COMSCORE_FILE_PATTERN", ".xlsx")
COMSCORE_CATALOGO_PELICULAS = env("COMSCORE_CATALOGO_PELICULAS")
COMSCORE_PROCESSED_LOG = env("COMSCORE_PROCESSED_LOG")
COMSCORE_RESULTADO_EXCEL = env("COMSCORE_RESULTADO_EXCEL")

SHOWTIME_PELICULAS_WATCH_FOLDER = env("SHOWTIME_PELICULAS_WATCH_FOLDER")
SHOWTIME_PELICULAS_FILE_PATTERN = env("SHOWTIME_PELICULAS_FILE_PATTERN", ".xlsx")
SHOWTIME_PELICULAS_PROCESSED_LOG = env("SHOWTIME_PELICULAS_PROCESSED_LOG")
SHOWTIME_PELICULAS_RESULTADO_EXCEL = env("SHOWTIME_PELICULAS_RESULTADO_EXCEL")

ORACLE_A1_WATCH_FOLDER = env("ORACLE_A1_WATCH_FOLDER")
ORACLE_A1_FILE_PATTERN = env("ORACLE_A1_FILE_PATTERN", ".csv")
ORACLE_A1_PROCESSED_LOG = env("ORACLE_A1_PROCESSED_LOG")
ORACLE_A1_RESULTADO_EXCEL = env("ORACLE_A1_RESULTADO_EXCEL")

SHOWTIME_PROMOS_WATCH_FOLDER = env("SHOWTIME_PROMOS_WATCH_FOLDER")
SHOWTIME_PROMOS_FILE_PATTERN = env("SHOWTIME_PROMOS_FILE_PATTERN", ".xlsx")
SHOWTIME_PROMOS_PROCESSED_LOG = env("SHOWTIME_PROMOS_PROCESSED_LOG")

watch_folder_PROMOS = env("SHOWTIME_PROMOS_WATCH_FOLDER")
file_pattern_PROMOS = env("SHOWTIME_PROMOS_FILE_PATTERN", ".xlsx")
processed_log_PROMOS = env("SHOWTIME_PROMOS_PROCESSED_LOG")
mapeo_PROMOS = env("MAPEO_PROMOS")